\# filepath: scripts/generate\_excel\_templates.py

import os

from datetime import datetime



def generate\_markdown\_tables():

&nbsp;   """Generate standardized competitive analysis templates in Markdown format."""

&nbsp;   

&nbsp;   templates = """# 📊 竞品分析标准化对标表 (Benchmarking Templates)



> 💡 \*\*使用指南\*\*：

> 以下表格可直接复制并粘贴到 Excel、Notion 或任何支持 Markdown 的编辑器中。

> 建议在每次启动竞品调研时，基于这些 template 建立标准化的 tracking system。



\## 1. 竞品基础信息对标 (Basic Information)



| 分析维度 | 我们的产品 | 竞品A | 竞品B | 竞品C |

| :--- | :--- | :--- | :--- | :--- |

| \*\*公司名称/背景\*\* | | | | |

| \*\*成立时间/阶段\*\* | | | | |

| \*\*融资轮次/金额\*\* | | | | |

| \*\*核心创始人背景\*\* | | | | |

| \*\*当前团队规模\*\* | | | | |

| \*\*核心数据表现\*\* | | | | |



\## 2. 产品定位与目标用户 (Positioning \& Target Audience)



| 分析维度 | 我们的产品 | 竞品A | 竞品B | 竞品C |

| :--- | :--- | :--- | :--- | :--- |

| \*\*Slogan/价值主张\*\* | | | | |

| \*\*核心解决痛点\*\* | | | | |

| \*\*目标用户画像\*\* | | | | |

| \*\*高频使用场景\*\* | | | | |

| \*\*市场切入点\*\* | | | | |



\## 3. 核心功能模块对比 (Feature Comparison)



| 功能模块 (Feature) | 我们的产品 | 竞品A | 竞品B | 竞品C | 差异化洞察 (Insights) |

| :--- | :--- | :--- | :--- | :--- | :--- |

| \*\*核心主路径功能\*\* | | | | | |

| \*\*用户留存功能\*\* | | | | | |

| \*\*商业变现功能\*\* | | | | | |

| \*\*社交/裂变功能\*\* | | | | | |

| \*\*特色微创新点\*\* | | | | | |



\## 4. 运营与核心数据对标 (Operational Metrics)



| 数据指标 (Metrics) | 我们的产品 | 竞品A | 竞品B | 竞品C | 数据来源 (Source) |

| :--- | :--- | :--- | :--- | :--- | :--- |

| \*\*预估 MAU / DAU\*\* | | | | | |

| \*\*App Store 排名\*\* | | | | | |

| \*\*全网搜索热度\*\* | | | | | |

| \*\*用户核心评价分\*\* | | | | | |

| \*\*次日/7日留存率\*\* | | | | | |



\## 5. 定价与盈利模式 (Pricing \& Monetization)



| 盈利模式 | 我们的产品 | 竞品A | 竞品B | 竞品C | 模式评估 |

| :--- | :--- | :--- | :--- | :--- | :--- |

| \*\*免费基础版 (Freemium)\*\* | | | | | |

| \*\*会员订阅费 (Subscription)\*\* | | | | | |

| \*\*广告变现 (Ads)\*\* | | | | | |

| \*\*增值服务 (Value-added)\*\* | | | | | |

| \*\*客单价预估 (ARPU)\*\* | | | | | |



\## 6. 营销与获客渠道分析 (User Acquisition \& Marketing)



| 获客渠道 | 我们的产品 | 竞品A | 竞品B | 竞品C | 渠道有效性评估 |

| :--- | :--- | :--- | :--- | :--- | :--- |

| \*\*SEO / ASO 策略\*\* | | | | | |

| \*\*信息流广告投放\*\* | | | | | |

| \*\*KOL / 社交裂变\*\* | | | | | |

| \*\*线下地推 / 合作\*\* | | | | | |

| \*\*PR 与品牌公关\*\* | | | | | |



\## 7. SWOT 分析汇总表 (SWOT Analysis)



| 维度 | 我们的产品 | 竞品A | 竞品B | 竞品C |

| :--- | :--- | :--- | :--- | :--- |

| \*\*优势 (Strengths)\*\* | | | | |

| \*\*劣势 (Weaknesses)\*\*| | | | |

| \*\*机会 (Opportunities)\*\*| | | | |

| \*\*威胁 (Threats)\*\* | | | | |



---

\*Generated by Competitive Analysis Skill System.\*

"""

&nbsp;   

&nbsp;   output\_dir = "outputs"

&nbsp;   if not os.path.exists(output\_dir):

&nbsp;       os.makedirs(output\_dir)

&nbsp;       

&nbsp;   filename = f"benchmarking\_templates\_{datetime.now().strftime('%Y%m%d')}.md"

&nbsp;   filepath = os.path.join(output\_dir, filename)

&nbsp;   

&nbsp;   with open(filepath, 'w', encoding='utf-8') as f:

&nbsp;       f.write(templates)

&nbsp;       

&nbsp;   print(f"✅ 成功生成 8 个标准数据对标表 (Standard Benchmarking Tables)！")

&nbsp;   print(f"📁 文件保存在: {filepath}")

&nbsp;   print("💡 You can directly import this markdown file into Notion or copy tables into Excel.")



if \_\_name\_\_ == "\_\_main\_\_":

&nbsp;   generate\_markdown\_tables()

